### ISSUE TITLE
running EPIC on Windows

### ISSUE THREAD

**Issue by smdb21** [BaderLab/EPIC#1]
Hi!
I was trying to use the Docker-based version to avoid to have to install all the python dependencies for Windows. 
So I had installed Docker in my computer (Windows 10), and then I got the bio-epic image installed. Then, to run it, following the instructions, I see that I have to run the "start-EPIC.sh", that is valid for MAX and Linux. OBviously, running it on Windows it fails because the DIR variable created on it doesn't get set because
`DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"`
BASH_SOURCE is not valid for Windows. 
Can you help me on this? Either could you give me the value of that DIR should contain or could you generate a ".bat" file for Windows users?
Thanks!!

**Comment by LucasHu** [comment]
Hi Salvador,

We solved the windows problem and I tested it on local windows machine, it works.

In the Cmd window enter the command given below: 

docker run --add-host="localhost:[192.168.142.172]" -p 8888:8888 -v "[C:\EPIC\EPIC-master-270818\MB_MQ_SW]:/home/jovyan/work/input" baderlab/bio-epic start-notebook.sh --NotebookApp.iopub_data_rate_limit=100000000 --NotebookApp.token=''

Replace [C:\EPIC\EPIC-master-270818\MB_MQ_SW] with the path to the input file folder (contains elution profile files) location.
Replace [192.168.142.172] with the IP address of your machine.

In the browser enter the url to run EPIC as jupyter notebook
http://localhost:8888/notebooks/EPIC.ipynb <http://localhost:8888/notebooks/EPIC.ipynb>

Let me know if this works for you, if so, I will add into the user manual.

best
Lucas

**Comment by smdb21** [comment]
Hi!
Thanks for your response.
However, I am having problems with it.
When I type the command as:
```
docker run --add-host="localhost:137.131.xxx.xxx" -p 8888:8888 -v "C:\Users\salvador\Desktop\epic\input:/home/jovyan/work/input" baderlab/bio-epic start-notebook.sh --NotebookApp.iopub_data_rate_limit=100000000 --NotebookApp.token=''
```
 (with my complete IP instead of the xxx.xxx), I got an error:
```
docker: Error response from daemon: error while creating mount source path '/host_mnt/c/Users/salvador/Desktop/epic/input': mkdir /host_mnt/c/Users/salvador/Desktop: permission denied.
```

Apparently is some permissions issue. I have tried to fix it by:
- enabling my "C" drive as shared in Docker (DONE)
- changing permissions on the folder "c/Users/salvador/Desktop/input"
But still doesn't work.
I will keep trying, but if you have any clue of what could cause this problem I would appreciate your help. Thanks!!

**Comment by smdb21** [comment]
Ok! I got it!
Reading some help in the internet, I found that I have to add full control permissions to the folder. But since it was complaining about "c/Users/salvador/Desktop/" and not "c/Users/salvador/Desktop/input" I figured that I had to do it at "c/Users/salvador/Desktop/"
The way to do it is:
 - right click on the folder (desktop in my case)
 - select Properties
 - select Security tab
 - click on "Edit..." button
 - click on "Add..." button
 - type "users" in the text box and click on "Check Names"
 - Click on OK
 - Select "Users" group on the list and enable full control checkbox at the bottom.
 - Click Apply and OK.

It loads now at http://localhost:8888/ !
Thanks for your help!
Salva.
