### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by lbwfff** [BaderLab/EPIC#13]
Hi, I'm using EPIC to analyse the example data and this is my code:

`python /scratch/lb4489/biotools/EPIC/src/main.py /scratch/lb4489/biotools/EPIC/test_data/elution_profiles /scratch/lb4489/biotools/EPIC/output -s 11101001 -c /scratch/lb4489/biotools/EPIC/test_data/Worm_reference_complexes.txt -n 20 -M RF`

However, I have encountered some problems in my analysis, and the following is the error message.

```
Start benchmarking
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
(['Precision', 'Recall', 'F-Measure', 'AUC PR', 'AUC ROC'], [0.7575205104831358, 0.47731188971855254, 0.5856236786469344, 0.44868823140617603, 0.7233773693279724])
to predict: 1131493
Traceback (most recent call last):
  File "/scratch/lb4489/biotools/EPIC/src/main.py", line 213, in <module>
    main()
  File "/scratch/lb4489/biotools/EPIC/src/main.py", line 198, in main
    pred_clusters.read_file("%s.clust.txt" % (output_dir))
  File "/scratch/lb4489/biotools/EPIC/src/GoldStandard.py", line 750, in read_file
    print "Average size of predicted complexes is: " + str((all_proteins_count)/i)
ZeroDivisionError: division by zero
```

This resulted in the creation of a blank Out.clust.txt file, while other results seemed to be fine. How should I fix this error？

Thanks,
LeeLee

**Comment by LucasHu** [comment]
Hi,

I just ran EPIC on my local Mac, it looks everything is fine:

Start benchmarking
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
Processing data...
(['Precision', 'Recall', 'F-Measure', 'AUC PR', 'AUC ROC'], [0.7631344612644702, 0.4922458357265939, 0.598463687150838, 0.4602754547024608, 0.7308443423319931])
to predict: 1131493
Loaded graph with 2978 nodes and 17032 edges
[====================] 100% Growing clusters from seeds...
[====================] 100% Finding highly overlapping clusters...
[====================] 100% Merging highly overlapping clusters...
Detected 417 complexes
Average size of predicted complexes is: 7.13669064748
# of complexes in reference dataset: 67
mmr	0.160350811017
overlapp	0.143885
simcoe	0.160671
mean_simcoe_overlap	0.170264
sensetivity	0.47764095917
ppv	0.3172715894868586
accuracy	0.389283837733
sep	0.167839838205

The command I was using is:

./EPIC/src/main.py -s 11101001 /Users/Desktop/EPIC/EPIC/test_data/elution_profiles/  -c /Users/Desktop/EPIC/EPIC/test_data/Worm_reference_complexes.txt /Users/Desktop/EPIC/EPIC/test_data/ -o PrefixName -M RF -n 6 -m EXP

I also asked my previous lab member to test EPIC on her computer, and she told me everything was good...

Could you give me more details about your error?

Best
L

**Comment by lbwfff** [comment]
Hi L,
 
Thanks for your reply! This is a strange issue, I can run it without problems on one server but not on the other, despite having a consistent conda environment on both servers.
