### ISSUE TITLE
Error running epic on docker

### ISSUE THREAD

**Issue by smdb21** [BaderLab/EPIC#2]
Hi!
I got to run epic with docker in a mac computer. However, when going through all the steps, I got an error in one as you can see in the attached screenshot. 
![Screen Shot 2019-07-16 at 12 11 23 PM](https://user-images.githubusercontent.com/11353022/61330587-d2059f80-a7d4-11e9-9942-068811dcd729.png)
Apparently, there is a division by zero because no proteins were read? (I think).
A sample input file (with the first 100 lines of the real one we used) is attached also here, so you may detect something wrong with it.
Thanks or your help!

[2019_05_17_SEC_NSAF.txt](https://github.com/BaderLab/EPIC/files/3399192/2019_05_17_SEC_NSAF.txt)

**Comment by LucasHu** [comment]
Hi Salvador,

I just tested the docker version software on my Mac, it seems to work well.

Did you put the start-EPIC.sh into the right directory.

See the first attached screenshot red part. The start-EPIC.sh should be put in the directory containing the input folder. For example, in the second screenshot, if the folder has elution profile files is elution_profiles, then you put the start-EPIC.sh in the directory contains this file folder. Don’t put the start-EPIC.sh file in the directory has the actual elution profile files.

best
Lucas

**Comment by smdb21** [comment]
Thanks for your prompt response!!

What we had was:
- Input _(folder)_
  - start-EPIC.sh
  - experiment_name _(folder)_
     - elution_profile.txt

So, if I am understanding correctly, we should have:
- start-EPIC.sh
- Input _(folder)_
  - experiment_name _(folder)_
     - elution_profile.txt

Right?
Thanks!!

PD: It would be great if we can run it in windows too (see other issue). thanks!

**Comment by LucasHu** [comment]
Hi Salvador,

The way I set is:
-start-EPIC.sh
-input (folder)
	-elution_profile_exp1.txt
	-elution_profile_exp2.txt
	…

let me know if it is working.

we are working on the windows issue right now. probably just need to have a different start-EPIC.sh script. We never had the window issue during delta-test from many users from multiple groups. 

apology.

best
Lucas
