### ISSUE TITLE
PPI prediction output 

### ISSUE THREAD

**Issue by zmb19** [BaderLab/EPIC#4]
Hello,

Just confirming that the Out.rf.exp.pred protein pairs exclude any that are used in the goldstandard list.

Thanks

**Comment by LucasHu** [comment]
Hi,

The set of predicted PPIs does not exclude the PPIs from gold standard.

But keep it in mind, EPIC did a lot of processing steps before machine learning, so if the two proteins in gold standard do not have well correlated elution profiles, they will be removed. So have a check if the two proteins have well correlated elution profiles if you didn't see them in the output.

Best

**Comment by zmb19** [comment]
Thanks!
