### ISSUE TITLE
False discovery rate

### ISSUE THREAD

**Issue by zmb19** [BaderLab/EPIC#5]
Hi,

I was wondering whether there was a way to determine the false discovery rate (FDR) of protein interactions.

Thanks

**Comment by LucasHu** [comment]
Hi zmb19,

Please update EPIC, I have included Precision, Recall, F-Measure, aucPR, aucROC and plots of PR curves and ROC curves into EPIC output for PPI level evaluation. Let me know if it works or not for you.

**Comment by zmb19** [comment]
Thanks LucasHu,

I am new to docker, how would I go about updating the container?

Thanks in advance

**Comment by LucasHu** [comment]
Hi,

Sorry for the late reply, you can check this page:
https://docs.docker.com/engine/reference/commandline/container_update/

The image just got updated, if you run EPIC in docker again, you should see these metrics.
Let me know if things work.

Best

**Comment by zmb19** [comment]
Thanks Lucas,

Running my data through today so I will hopefully have it completed by tomorrow. Where should I look for these outputs, are they in a file or show as output on the jupyter notebook?

Thanks again,
Zoe

**Comment by LucasHu** [comment]
Hi Zoe,

The metrics should be printed out in Notebook.

The figures of curves are saved in the output directory.

Best

**Comment by zmb19** [comment]
Hi Lucas,

I re-downloaded the container and ran my data through last night and it seems as though the jupyter notebook gave the same output as before (no new ROC curves in my output folder).
Do you know how I can check if the container has been updated?

Thanks,
Zoe

**Comment by LucasHu** [comment]
Hi Zoe,

Sorry, I forgot to change the code in the notebook file... It just got updated.

Could you try it with just one elution profile instead of all. I wanna make sure it works well on your side.

Best

**Comment by zmb19** [comment]
Hi again!

Ran a smaller file and came across an error at the "Prediction protein clusters" heading:
![Screen Shot 2019-10-03 at 11 09 28 am](https://user-images.githubusercontent.com/52184081/66092271-bf7a5580-e5ce-11e9-8acd-589da07e4585.png)

I changed the "gs" int the code to "GS" but then got another error:
![Screen Shot 2019-10-03 at 11 11 37 am](https://user-images.githubusercontent.com/52184081/66092286-d5881600-e5ce-11e9-8328-5abd7de8c202.png)

Hope this helps, still no ROC curves in the output folder but I'm assuming that I haven't reached the chunk that codes them yet.

Thanks so much for your help

**Comment by LucasHu** [comment]
Hi Joe, 

Please change that line to:

print utils.cv_bench_clf(scoreCalc, clf, all_gs, output_dir, verbose=False, format="pdf", folds=5)

I have tested it in my labtop, it works well. I will later on update the Docker image.

Let me know if it works on your computer. Try one elution file first before trying all elution files.

best

**Comment by zmb19** [comment]
It worked!

Thanks so much!!!!
