### ISSUE TITLE
Kernel dying

### ISSUE THREAD

**Issue by leahvschaffer** [BaderLab/EPIC#7]
Hello, I am trying to run the Jupyter notebook with Docker and the kernel keeps dying when I run the cell under Calculating co-elution scores... do you know if this may be a memory issue or have you experienced this before? Thank you!!

**Comment by LucasHu** [comment]
Hi Leah,

The docker version EPIC software has been tested by multiple users in many computers. We never experienced this problem before…I suspect it might be something related to your computer. Could you tell me the error code reported in Jupiter notebook?

Meanwhile, if possible, try it on another computer to see if it works...

Best
Lucas

**Comment by leahvschaffer** [comment]
OK FYI it ran fine with the example files and a new file with fewer intensity values so I think it was maybe a RAM issue. Thank you!
