### ISSUE TITLE
suggestion for installation instructions

### ISSUE THREAD

**Issue by smdb21** [BaderLab/EPIC#8]
At least in my configuration with windows, I needed RTools installed in my computer. The user has to install the appropriate version at https://cran.r-project.org/bin/windows/Rtools/history.html depending on the R version it has.
I am suggesting including this in the installation instructions, just in case someone faces the same problem. Thanks!

**Comment by LucasHu** [comment]
Hi,

Thanks for your suggestion. I personally use Mac, which never asked me to install RTools, or I installed beforehand.

I will add your comments in the instructions.

Best
Lucas
